version: "2"
services:
    server-redis:
        image: redis
        ports:
            - "6379:6379"
    server-mongo:
        image: mongo
        volumes:
            - ./server-mongo:/data/db
        ports:
            - "27017:27017"
            - "27018:27018"
    # server-mysql:
    #     image: mysql
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=1234qwer
    #         - MYSQL_USER=test
    #         - MYSQL_PASSWORD=1234qwer
    #     volumes:
    #         - ./server-mysql:/var/lib/mysql
    #     ports:
    #         - "3306:3306"
    # server-pma:
    #     image: phpmyadmin/phpmyadmin
    #     environment:
    #         - PMA_HOST=server-mysql
    #     ports:
    #         - "8080:80"
    server-flask:
        build: ./server-flask
        image: mercuryparadise/server-flask
        command: python /code/src/app.py
        volumes:
            - ./server-flask:/code
        ports:
            - "5000:5000"

